name: Lint

on:
  push:
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Run ESLint
        run: npx eslint "**/*.js"